### ISSUE TITLE
Script crashes on DB server reboot

### ISSUE THREAD

**Issue by JVCubed** [JVCubed/Honeypot#4]
When the SQL get's a reboot the scripts crashes with the following error:

> Apr 10 15:13:14 _host_ python3[21436]: Traceback (most recent call last):
Apr 10 15:13:14 _host_ python3[21436]:   File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection_cext.py", line 233, in _o>
Apr 10 15:13:14 _host_ python3[21436]:     self._cmysql.connect(**cnx_kwargs)
Apr 10 15:13:14 _host_ python3[21436]: _mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on '_IP_' (111)
Apr 10 15:13:14 _host_ python3[21436]: During handling of the above exception, another exception occurred:
Apr 10 15:13:14 _host_ python3[21436]: Traceback (most recent call last):
Apr 10 15:13:14 _host_ python3[21436]:   File "/root/sshLog.py", line 20, in <module>
Apr 10 15:13:14 _host_ python3[21436]:     mydb = mysql.connector.connect(
Apr 10 15:13:14 _host_ python3[21436]:   File "/usr/local/lib/python3.8/dist-packages/mysql/connector/__init__.py", line 277, in connect
Apr 10 15:13:14 _host_ python3[21436]:     return CMySQLConnection(*args, **kwargs)
Apr 10 15:13:14 _host_ python3[21436]:   File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection_cext.py", line 86, in __i>
Apr 10 15:13:14 _host_ python3[21436]:     self.connect(**kwargs)
Apr 10 15:13:14 _host_ python3[21436]:   File "/usr/local/lib/python3.8/dist-packages/mysql/connector/abstracts.py", line 1003, in connect
Apr 10 15:13:14 _host_ python3[21436]:     self._open_connection()
Apr 10 15:13:14 _host_ python3[21436]:   File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection_cext.py", line 235, in _o>
Apr 10 15:13:14 _host_ python3[21436]:     raise errors.get_mysql_exception(msg=exc.msg, errno=exc.errno,
Apr 10 15:13:14 _host_ python3[21436]: mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on '10.0.0.2' (11>
Apr 10 15:13:14 _host_ systemd[1]: sshLog.service: Main process exited, code=exited, status=1/FAILURE

This issue is happening in the following line, specifically in de `mydb.commit()`:
https://github.com/JVCubed/log-to-mysql/blob/ed0dde12d497d103ac7411eaaf35084b4f057891/sshLog/logSSH.py#L35-L40

The error can be catched with using a try except in the function:
```python
def SQLadd(datetime, user, ip, country):
  try:
    sql = "INSERT INTO ssh (time, username, srcIp, srcCountry, dstServer, dstCountry) VALUES (STR_TO_DATE(%(date)s,'%Y %b %d %k:%i:%s'), %(name)s, %(srcIpAddress)s, %(srcCountry)s, %(dstServer)s, %(dstCountry)s)"
    mycursor.execute(sql, { 'date': datetime, 'name': user, 'srcIpAddress': ip, 'srcCountry': country, 'dstServer': DBuser, 'dstCountry': dstCountry})

    mydb.commit()
  except mysql.connector.DatabaseError as e:
    print(f'Error: {e}')
```

To let the script continue it have to detect the server is back online. To do so the connection needs to be reestablished.

It would be nice if this issue can be solved by keeping the INSERT INTO statements while there is no connection, but it is not giving any issues if some data is lost.

**Comment by JVCubed** [comment]
This issue is solved by adding a while loop and breaking it after a successful commit. If a MySQL connector exception is thrown it will retry till the database server is back online. Only after a successful commit tailhead will continue to read the logs.
```python
def SQLadd(datetime, user, ip, country):
    while True:
        try:
            # Try to create connection
            mydb, mycursor = mysql_connection()
            sql = "INSERT INTO ssh (time, username, srcIp, srcCountry, dstServer, dstCountry) VALUES (STR_TO_DATE(%(date)s,'%Y %b %d %k:%i:%s'), %(name)s, %(srcIpAddress)s, %(srcCountry)s, %(dstServer)s, %(dstCountry)s)"
            mycursor.execute(sql, { 'date': datetime, 'name': user, 'srcIpAddress': ip, 'srcCountry': country, 'dstServer': config['DEFAULT']['sqluser'], 'dstCountry': config['HOST']['dstcountry']})
            mydb.commit()
            break
        except mysql.connector.DatabaseError as e:
            print(e)
            continue
        except Exception as e:
            print(e)
            break
```
